name: Windows-Build

on:
  pull_request:
  push:

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest]
        arch: [x64]
        mode: [debug, releasedbg]

    runs-on: ${{ matrix.os }}
    if: "!contains(github.event.head_commit.message, 'ci skip')"

    env:
      QT_VERSION: '5.15.2'
      OBS_VERSION: '26.0.0'
      CMAKE_GENERATOR: 'Visual Studio 16 2019'

    steps:
    - uses: actions/checkout@v2

    # Install Qt
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: ${{ env.QT_VERSION }}

    # Build obs-studio
    - name: 'Clone OBS'
      uses: actions/checkout@v2
      with:
        repository: obsproject/obs-studio
        path: ${{ github.workspace }}/obs-studio
        submodules: 'recursive'
        fetch-depth: 0 # for tags

    # Checkout OBS to the wanted version
    - name: 'Checkout OBS-Studio release (${{ env.OBS_VERSION }})'
      shell: bash
      working-directory: ${{ github.workspace }}/obs-studio
      run: |
        git checkout ${{ env.OBS_VERSION }}
        git submodule update

    # Install OBS dependencies
    - name: Install OBS dependencies
      working-directory: ${{ github.workspace }}
      run: |
        curl https://obsproject.com/downloads/dependencies2019.zip --output dependencies2019.zip
        mkdir obsdeps
        tar -xv -C obsdeps -f dependencies2019.zip

    # Configure and build obs
    - name: 'Build OBS-Studio'
      working-directory: ${{ github.workspace }}/obs-studio
      shell: bash
      run: |
        mkdir ./build64
        cd ./build64
        cmake -G "${{ env.CMAKE_GENERATOR }}" -A x64 -DDepsPath=${{ github.workspace }}/obsdeps/win64 -DQTDIR=${{ env.Qt5_DIR }} -DDISABLE_PLUGINS=YES -DENABLE_SCRIPTING=NO ..
        msbuild /m /p:Configuration=RelWithDebInfo ./libobs/libobs.vcxproj

    # Install xmake
    - name: Setup xmake
      uses: xmake-io/github-action-setup-xmake@v1

    # Prepare environment
    - name: Configure build
      run:
        printf "LibObs = {\n  Include = [[${{ github.workspace }}/obs-studio/libobs]],\n  Lib64 = [[${{ github.workspace }}/obs-studio/build64/libobs]]\n}\n\nObsPlugins={}" > config.lua

    # Update xmake repository (in order to have the file that will be cached)
    - name: Update xmake repository
      run: xmake repo --update

    # Cache xmake dependencies
    - uses: actions/cache@v2
      with:
        path: ~/.xmake/packages
        key: ${{ runner.os }}-${{ matrix.arch }}-${{ matrix.mode }}-${{ hashFiles('xmake.lua', 'xmake-repo') }}-${{ hashFiles('~/.xmake/xmake.conf') }}-${{ hashFiles('~/.xmake/repositories/**') }}

    # Setup compilation mode and install project dependencies
    - name: Configure xmake and install dependencies
      run: xmake config --arch=${{ matrix.arch }} --mode=${{ matrix.mode }} --yes --verbose

    # Build the plugin
    - name: Build obs-kinect
      run: xmake

    # Install the result files
    - name: Install obs-kinect
      run: xmake package -vo package

    # Upload artifacts
    - uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.os }}-${{ matrix.arch }}-${{ matrix.mode }}
        path: package
